# Generated by Django 3.2.5 on 2021-09-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210913_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='parentusername',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
