# Generated by Django 3.2.5 on 2021-09-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_studentdata_parentusername'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parentdata',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('guardian_of', models.CharField(max_length=255)),
                ('id', models.CharField(default=' ', max_length=100, primary_key='True', serialize=False)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('username', models.CharField(default=' ', max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('studentusername', models.CharField(default=' ', max_length=20)),
                ('profile_pic', models.ImageField(default=' ', upload_to='home/images')),
            ],
        ),
    ]
