# Generated by Django 3.2.5 on 2021-09-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_parentdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentdata',
            name='roll',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
