# Generated by Django 3.2.6 on 2021-09-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('details', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=300)),
                ('status', models.CharField(choices=[('A', 'Accept'), ('P', 'Pending'), ('R', 'Reject')], max_length=1)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
