# Generated by Django 3.2.5 on 2021-09-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0002_remove_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('A', 'Accept'), ('P', 'Pending'), ('R', 'Reject')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
