# Generated by Django 3.2.5 on 2021-09-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0003_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('A', 'Accept'), ('P', 'Pending'), ('R', 'Reject')], default='P', max_length=1),
        ),
    ]
