# Generated by Django 3.2.6 on 2021-09-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('details', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=300)),
                ('uploadfile', models.FileField(null=True, upload_to='')),
                ('status', models.CharField(max_length=10)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
