# Generated by Django 3.2.6 on 2021-09-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='uploadfile',
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Accept'), (3, 'Reject')]),
        ),
    ]
